config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_USERNAME'])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_PASSWORD']))
  end unless Rails.env.development?
  mount Sidekiq::Web, at: "/sidekiq"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :circles do
    scope module: 'circle' do
      resource :admin do
        get :roles, :working_groups, :invite, :sponsors, :notifications
        post :activate_member
      end

      resources :members do
        put :activate, :block, :unblock, on: :member
        resources :comments, only: [:create, :index, :destroy, :update]
      end

      resources :roles, :organizers

      resources :supplies do
        put :complete, :volunteer, :decline, :reopen
        resources :comments, only: [:create, :index, :destroy, :update]

        post :invite
      end

      resources :working_groups do
        get :edit_members,    path: '/edit/members'
        get :edit_organizers, path: '/edit/organizers'
        get :edit_projects, path: '/edit/projects'
        patch :add_user
        delete :remove_user

        patch :join, :leave, :activate, :disable

        resources :tasks, only: [:new]
        resources :supplies, only: [:new]
        resources :projects, only: [:new]
      end

      resources :taskables do
        collection do
          get :volunteer
          get :organizer
        end
      end


      resources :tasks do
        collection do
          get :my
          get :open
          get :completed
        end
        resources :comments, only: [:create, :destroy, :update, :index]

        # FIXME task roles need a controller of their own!
        put   :volunteer, :assign_volunteer, :unassign_volunteer, :decline, :complete, :reopen, :clone
        patch :volunteer, :assign_volunteer, :unassign_volunteer, :decline, :complete, :reopen, :clone

        post :invite
      end

      resources :projects do
        post :invite
        put :complete, :reopen
        resources :comments, only: [:create, :destroy, :update, :index]
        resources :tasks, only: [:new]
        resources :supplies, only: [:new]
        resources :files, only: [:create, :destroy, :show]
        resources :files, path: '/files/:uploadable', only: [:new]
        resources :documents, only: :index
      end
      resources :files, only: [:create, :edit, :destroy]
      resources :files, path: '/files/:uploadable', only: [:new]

      resources :documents, only: :index
    end

    resources :files, only: [:show, :update]

  end

  get '/styles', to: 'styleguide#show'

  namespace :user do
    resources :identities
  end

  namespace :api do
    resources :circles, only: [:index]
  end

  get "/register",  to: "user/identities#new", :as => "register"
  post "/register", to: "user/identities#create"

  get  "/join/:circle_id", to: 'circle/invite_flow#join',  as: 'join_circle'
  post "/join/:circle_id", to: 'circle/invite_flow#submit'

  get "/token/:token_code", to: "tokens#handle_token", as: "handle_token"

  scope module: "user" do
    # FIXME none of the resource actions may be needed anymore.
    resources :accounts do
      get :change_password, :switch_circle
      patch :update_password
    end
  end

  scope module: "public" do
    get  "/reset_password", to: 'reset_password_flow#reset_password', as: 'public_reset_password'
    post "/reset_password", to: 'reset_password_flow#submit'
    get "/reset_password/confirmation", to: 'reset_password_flow#confirmation', as: 'public_reset_password_confirmation'
  end

  namespace :public do
    resources :circles, only: [:index, :new, :create] do
      post :join, on: :collection
      get "membership_inactive/:status", action: :membership_inactive, as: :inactive_circle_membership
    end
  end

  get  "/login",  to: "sessions#new",     as: "login"
  post "/login",  to: "sessions#create"
  get  "/logout", to: "sessions#destroy", as: "logout"

  root to: "sessions#new"
  ActiveAdmin.routes(self)
end

app/controllers/api/circles_controller.rb
class Api::CirclesController < ApplicationController
  layout false
  skip_authorization_check

  def index
    @center = params[:location].present? ? Location.location_from(params[:location]) : current_user.location
    locations = Location.near(@center).to_a
    @circles = Circle.joins(:address).where(addresses: { location_id: locations.uniq } )
  end
end

app/controllers/circle/admins_controller.rb
class Circle::AdminsController < ApplicationController
  include HasCircle
  before_action :ensure_logged_in

  before_action do
    authorize! :manage, current_circle
  end

  def show
    @form = Circle::Update.new(user: current_user, circle: current_circle)
  end

  def roles
  end

  def working_groups
  end

  def invite
  end

  def notifications
    @form = Circle::Update.new(user: current_user, circle: current_circle)
  end

  def sponsors
  end

  helper_method def tab_class key
    (action_name == key) ? "#{key} selected" : key
  end
end

app/controllers/circle/comments_controller.rb
class Circle::CommentsController < ApplicationController
  layout "internal"
  before_action :ensure_logged_in
  before_action :set_comment, :only => [:destroy, :update]

  include HasCircle

  def index
    authorize! :read, current_item
    if can? :create, Comment, current_item, current_circle
      @form = Comment::Create.new(commenter: current_user, item: current_item, comment: Comment.new)
    end
    render layout: false
  end

  def create
    authorize! :create, Comment, current_item, current_circle

    @comment = Comment.new
    @form = Comment::Create.new(params[:comment], commenter: current_user, item: current_item, comment: @comment)

    outcome = @form.submit

    if outcome.success?
      redirect_to circle_commentable_path(current_circle, current_item),
      notice: t('flash.created', name: Comment.model_name.human)
    else
      redirect_to circle_commentable_path(current_circle, current_item),
      alert: t('flash.failed.create', name: Comment.model_name.human)
    end
  end

  def update
    authorize! :update, Comment, current_item, current_circle

    @form = Comment::Update.new(params[:comment], commenter: current_user, item: current_item, comment: @comment)

    outcome = @form.submit

    respond_to do |format|
      if outcome.success?
        format.html { redirect_to circle_commentable_path(current_circle, current_item) }
        format.json { head :no_content }
      else
        format.html { redirect_to circle_commentable_path(current_circle, current_item) }
        format.json { render json: outcome.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :update, Comment, current_item, current_circle

    @comment.destroy

    redirect_to circle_commentable_path(current_circle, current_item),
                notice: t('flash.destroy', name: Comment.model_name.human)
  end

  helper_method def current_item
    @item ||= if params[:supply_id].present?
                Supply.find(params[:supply_id])
              elsif params[:member_id].present?
                User.find(params[:member_id])
              elsif params[:project_id].present?
                Project.find(params[:project_id])
              else
                Task.find(params[:task_id])
              end
  end

  helper_method def page
    @page ||= OpenStruct.new.tap do |page|
    end
  end

  private

    def set_comment
      @comment = current_item.comments.find(params[:id])
    end

    def circle_commentable_path(circle, item)
      if item.is_a? Supply
        circle_supply_path(circle, item)
      elsif item.is_a? User
        circle_member_path(circle, item)
      elsif item.is_a? Project
        circle_project_path(circle, item)
      else
        circle_task_path(circle, item)
      end
    end
end

app/controllers/circle/documents_controller.rb
class Circle::DocumentsController < ApplicationController

  skip_authorization_check # TODO: REMOVE

  include HasCircle

  before_action :ensure_logged_in
  before_action :set_back_path, only: [:index]

  def index
    authorize! :read, current_circle

    @circle_files = current_circle.files.select{ |f| can?(:read, f) }
    @circle_links = [] # current_circle.links.select{ |f| can?(:read, f) }

    @working_group_files = FileUpload.where(uploadable: current_circle.working_groups).select { |f| can?(:read, f) }
    @working_group_links = [] # links.select{ |f| can?(:read, f) }

    @project_files = FileUpload.where(uploadable: current_circle.projects).select { |f| can?(:read, f) }
    @project_links = [] # current_circle.links.select{ |f| can?(:read, f) }
  end
end

app/controllers/circle/files_controller.rb
class Circle::FilesController < ApplicationController
  include HasCircle

  before_action :ensure_logged_in, except: :show
  skip_before_action EnsureActiveUser, only: :show

  skip_authorization_check

  def show
    file = FileUpload.find(params[:id])
    authorize! :read, file

    if stale? file
      expires_in(1.hour, public: false)
      filename = file.name + file.file_extension
      disposition = params.has_key?(:download) ? 'attachment' : 'inline'
      send_data file.read, disposition: disposition, filename: filename, type: file.file_content_type
    end

  rescue => e
    Rails.logger.warning "#{e.message}: user: #{current_user.id} file: #{params[:id]}"
    render nothing: true, status: :not_found
  end

  def new
    @form = FileUpload::CreateForm.new(uploadable_gid: params[:uploadable], redirect_path: URI(request.referer || '').path)
    authorize! :manage, @form.uploadable
  end

  def create
    @form = FileUpload::CreateForm.new(params[:file_upload], uploader: current_user)
    authorize! :manage, @form.uploadable
    outcome = @form.submit
    if outcome.success?
      redirect_to @form.redirect_path, notice: t('flash.file_uploads.created')

    else
      errors.add outcome.errors
      render :new
    end
  end

  def edit
    file = FileUpload.find(params[:id])
    authorize! :manage, file
    @form = FileUpload::UpdateForm.new(file_upload: file, redirect_path: URI(request.referer || '').path)
  end

  def update
    file = FileUpload.find(params[:id])
    authorize! :manage, file
    @form = FileUpload::UpdateForm.new(params[:file_upload], file_upload: file)
    outcome = @form.submit
    if outcome.success?
      redirect_to @form.redirect_path, notice: t('flash.file_uploads.updated')

    else
      errors.add outcome.errors
      render :edit
    end
  end

  def destroy
    FileUpload::Destroy.run!( user: current_user, file: FileUpload.find(params[:id]) )
    redirect_to :back
  end
end

app/controllers/circle/invite_flow_controller.rb
class Circle::InviteFlowController < ApplicationController
  skip_authorization_check
  layout 'public'

  def join
    form
  end

  def submit
    outcome = if current_user.present?
      Circle::Join.run(user: current_user, circle_id: circle.id)
    else
      form.submit
    end

    if outcome.success?
      login(outcome.result) unless current_user
      redirect_to circle_path(circle)

    else
      errors.add outcome.errors
      render :join
    end
  end

  helper_method def form
    @form ||= User::Create.new(params[:user] || {}, circle: circle)
  end

  helper_method def circle
    @circle ||= Circle.find_by(id: params[:circle_id])
  end
  alias_method :current_circle, :circle

  before_action do
    @skip_registration_links = true
    redirect_to root_url unless circle.present?
  end
end

app/controllers/circle/members_controller.rb
#
# a "Member" is a user in a circle. Technically this is implemented
# with roles; a user is member in a circle if (s)he has a circle_role.
#
class Circle::MembersController < ApplicationController

  before_action :ensure_logged_in
  before_action :set_back_path, only: :index

  include HasCircle

  def index
    authorize! :read, current_circle
    @members    = active_users.select { |member| can?(:read, member, current_circle) }
    @organizers = organizers.select { |member| can?(:read, member, current_circle) }
    @totals     = { members: active_users.count, organizers: organizers.count }
    respond_to do |format|
      format.html
      format.csv { send_data(generate_csv(@members)) }
      format.pdf do
        render  pdf: "#{current_circle.name}_" + t("pdf.list") + "_" + Date.today.to_formatted_s(:number),
                template: 'circle/members/pdf.slim',
                layout: 'pdf.slim',
                locals: { members: @members },
                orientation: 'Landscape'
      end
    end
  end

  def show
    authorize! :read, current_member, current_circle
    if can? :create, Comment.new, current_member, current_circle
      @form = Comment::Create.new(commenter: current_user, item: current_member, comment: Comment.new)
    end
  end

  def edit
    authorize! :edit, current_member, current_circle
    @form = User::Update.new(user: current_member, current_circle: current_circle)
  end

  def update
    authorize! :edit, current_member, current_circle
    @form = User::Update.new(params[:user], user: current_member, current_circle: current_circle)
    outcome = @form.submit
    errors.add outcome.errors
    if outcome.success?
      flash[:notice] = t("flash.user.account.saved")
      redirect_to circle_member_url(current_circle, current_member)
    else
      flash[:error] = t("flash.user.account.save-failed")
      render :edit
    end
  end

  def activate
    authorize! :activate_member, current_circle
    outcome = Circle::Member::Activate.run(params.merge(admin: current_user))
    if request.xhr?
      head (outcome ? :ok : :unprocessable_entity)
    else
      redirect_to circle_member_path(current_circle, current_member)
    end
  end


  def block
    authorize! :block, current_member, current_circle
    Circle::Member::Block.run(params.merge(admin: current_user))
    redirect_to circle_member_path(current_circle, current_member)
  end


  def unblock
    authorize! :unblock, current_member, current_circle
    Circle::Member::Unblock.run(params.merge(admin: current_user))
    redirect_to circle_member_path(current_circle, current_member)
  end


  helper_method def current_member
    @current_member ||= current_circle.users.find(params[:id])
  end

  private

  def active_users
    @_active_users ||= current_circle.users.active
      .includes(:identity, :working_groups, :circle_roles)
      .order('last_name asc')
  end

  def generate_csv(members)
    template = "circle/members/index.csv.slim"
    content = render_to_string(template, layout: false, locals: { members: members })
  end

  def organizers
    @_organizers ||= begin
      circle_organizers = User.
          select('users.id, count(*) as role_count').
          joins(:circle_roles).
          where(circle_roles: { role_type: Circle::Role::ORGANIZER_TYPE_IDS, circle: current_circle }).
          group('users.id')

      working_group_organizers = User.
          select('users.id, count(*) as role_count').
          joins(:working_group_roles).
          where(working_group_roles: { role_type: WorkingGroup::Role::ORGANIZER_TYPE_IDS, working_group_id: current_circle.working_groups }).
          group('users.id')

      counts = (circle_organizers + working_group_organizers).each_with_object(Hash.new) do |user, obj|
        obj[user.id] ||= 0
        obj[user.id] += user.role_count
      end

      all_organizers = User.where(id: counts.keys).includes(:identity, :working_groups, :circle_roles)

      all_organizers.sort_by { |u| -counts[u.id] }
    end
  end

end

app/controllers/circle/organizers_controller.rb
class Circle::OrganizersController < ApplicationController

  skip_authorization_check # TODO: REMOVE

  include HasCircle

  before_action :ensure_logged_in
  before_action :set_back_path, only: [:index]

  def index
    circle_organizers = User.
      select('users.id, count(*) as role_count').
      joins(:circle_roles).
      where(circle_roles: { role_type: Circle::Role::ORGANIZER_TYPE_IDS, circle: current_circle }).
      group('users.id')

    working_group_organizers = User.
      select('users.id, count(*) as role_count').
      joins(:working_group_roles).
      where(working_group_roles: { role_type: WorkingGroup::Role::ORGANIZER_TYPE_IDS, working_group_id: current_circle.working_groups }).
      group('users.id')

    counts = (circle_organizers + working_group_organizers).each_with_object(Hash.new) do |user, obj|
      obj[user.id] ||= 0
      obj[user.id] += user.role_count
    end

    all_organizers = User.where(id: counts.keys).includes(:identity, :working_groups, :circle_roles)

    @members = all_organizers.sort_by{|u| -counts[u.id] }
  end
end

app/controllers/circle/roles_controller.rb
class Circle::RolesController < ApplicationController
  include HasCircle
  before_action :ensure_logged_in
  def create
    authorize! :manage, current_circle

    current_circle.roles.create role_params

    redirect_to roles_circle_admin_path(current_circle)
  end

  def destroy
    authorize! :manage, current_circle

    role = current_circle.roles.find(params[:id])
    role.destroy

    redirect_to roles_circle_admin_path(current_circle)
  end

  private
  def role_params
    params[:circle_role].permit(:name, :role_type, :user_id)
  end

end

app/views/circle/tasks/_edit_actions.slim
.dropdown.task-edit-menu
  
  / showing/hiding the dropdown menu is implemented with CSS only. 
  / the checked state of this checkbox controls which CSS rules are applied to the 
  / menu, thus toggling it's visiblity.
  input id='task-edit-selector' type='checkbox' class='menu-selector'

  label for='task-edit-selector'
    .button.button-super
      i.fi-chevron-bottom
      = t('.edit_button_dropdown', model: item.model_name.human)

  .menu
    - if can? :edit, item
      = link_to(edit_circle_task_path(circle, item)) do
        = t('helpers.edit', model: item.model_name.human)
    - if can? :complete, item
      = link_to(circle_task_complete_path(circle, item), method: :put) do
        = t('helpers.complete', model: item.model_name.human)
    - if can? :reopen, item
      = link_to(circle_task_reopen_path(circle, item), method: :put) do
        = t('helpers.reopen', model: item.model_name.human)
    - if can? :clone, item
      = link_to(circle_task_clone_path(circle, item), method: :put) do
        = t('helpers.clone', model: item.model_name.human)
    - if can? :delete, item
      - options = {data: {:confirm => t('helpers.confirm.task.delete')}, method: :delete}
      = link_to(circle_task_path(circle, item), options) do
        = t('helpers.delete', model: item.model_name.human)

app/views/circle/tasks/_form.slim
= form_for [current_circle, @form] do |f|
  - if errors.present?
    .form-introduction.error
      p= t('error_correction')


  .field-row.single
    .field.required class=errors.css(:name)
      = f.label :name
      = f.text_field :name, placeholder: true
      = errors.formatted_message_for(:name)

  .field-row.single
    .field.required class=errors.css(:description)
      = f.label :description
      = f.text_area :description
      = errors.formatted_message_for(:description)

  .field-row
    .field.required class=errors.css(:volunteer_count_required)
      = f.label :volunteer_count_required
      = f.select :volunteer_count_required do
        = options_for_select(1..10, @form.volunteer_count_required)
      = errors.formatted_message_for(:volunteer_count_required)

    .field.required
      = f.label :duration
      = f.select :duration do
        = options_for_select(@form.duration_options, @form.duration)

  .field-row-3

    / select scheduling type

    .field-3
      = f.label :scheduling_type
      = f.select :scheduling_type do
        = options_for_select(@form.scheduling_type_options, @form.scheduling_type)
      = errors.formatted_message_for(:scheduling_type)

    / start date & time (hidden by default)

    .field-3.between-element class=errors.css(:start_date)
      = f.label :start_date
      = f.text_field :start_date_string, class: :xd_datepicker

    .field-3.between-element class=errors.css(:start_time)
      = f.label :start_time
      = f.text_field :start_time, class: :xd_timepicker, placeholder: t('.placeholder_optional')

    / end date & time (always visible)

    .field-3.required class=errors.css(:due_date)
      = f.label :date, class: 'at-element'
      = f.label :due_date, class: 'between-element'
      = f.text_field :due_date_string, class: :xd_datepicker

    .field-3 class=errors.css(:due_time)
      = f.label :time, class: 'at-element'
      = f.label :due_time, class: 'between-element'
      = f.text_field :due_time, class: :xd_timepicker, placeholder: t('.placeholder_optional')

  - if errors.present?
    .field-row.single
      .field
        - %i(start_date start_time due_date due_time).each do |field|
          - if errors.formatted_message_for(field).present?
            = errors.formatted_message_for(field)
            br

  .field-row

    .field class=errors.css(:primary_location)
      = f.label :primary_location
      = f.text_field :primary_location
      = errors.formatted_message_for(:primary_location)


  .field-row
    .field.required class=errors.css(:working_group)
      = f.label :working_group_id
      - unless @form.working_group_disabled?
        = f.collection_select :working_group_id, @form.available_working_groups, :id, :name, {}
        = errors.formatted_message_for(:working_group)
      - else
        = f.hidden_field :working_group_id
        = text_field_tag :disabled, @form.working_group.name, disabled: true

    .field.required class=errors.css(:organizer_id)
      = f.label :organizer_id
      = f.grouped_collection_select(:organizer_id, @form.available_working_groups, :users, :name, :id, :name)
      = errors.formatted_message_for(:organizer_id)


  .field-row
    .field
      = f.label :project
      = taskable_project_select(@form.available_projects, selected_project: @form.project, tag_id: 'task_project_id', tag_name: 'task[project_id]')
      = errors.formatted_message_for(:project_id)


  = f.hidden_field(:original_task_id, value: @form.original_task_id)
  .submit-row
    = f.submit
    - if @form.task.persisted?
      = submit_tag(t('.update_and_notify'), name: 'send_notifications', class: 'button-primary', data: {disable_with: t('.update_and_notify') })
    = link_to(t('task_edit.cancel'), :back)

app/views/circle/tasks/_list.slim
- title ||= ""
- list_id ||= nil

h3
  = title

.rich-table id=list_id
  - if tasks.present?
    - tasks.each do |task|
      - if can? :read, task
        = render 'circle/tasks/list_item', task: task

  -else
    = t('.no-tasks')

app/views/circle/tasks/_list_item.slim
/ TODO: this is bad... but better than before
- task = ::TaskPresenter.new(task)

div.item href=circle_task_path(task.circle, task) class=task.css
  .item-details
    == cell(:calendar_leaf, task.due_date)

    .item-content
      .item-title = task.name
      .subtitle
        - if task.message.present?
          span.bullet &bullet;
          span.status-message = task.message
    .item-stats
      .item-assignees
        - task.volunteers.take(3).each do |volunteer|
          == cell(:user_icon, volunteer, circle: current_circle, link: true)
        - if task.volunteers.size > 3
          .more.user-icon-container = '...'
      .task-badge.task-badge--users
        i
        = "#{task.volunteers.count}/#{task.volunteer_count_required}"

      .task-badge.task-badge--comments
        i
        = task.comments.human.count

app/views/circle/tasks/_task_list.slim
- title ||= ""
- list_id ||= nil

h3
  = title

.task-list id=list_id
  - if tasks.present?
    - tasks.each do |task|
      - if can? :read, task
        = render partial: 'circle/tasks/task_list_item', locals: { circle: circle, task: task }

  -else
    = t('.no-tasks')

app/views/circle/tasks/_task_list_item.slim
/ TODO: this is bad... but better than before
- task = ::TaskPresenter.new(task)

div.task href=circle_task_path(current_circle, task) class=task.css
  .task-details
    .task-date
      .month= task.due_date_month
      .day
        span.day_number= task.due_date_day
        span.day-of-week= task.due_date_day_of_week

    .task-content
      .task-title= task.name
      .subtitle
        - if task.message.present?
          span.bullet &bullet;
          span.status-message = task.message
    .task-stats
      .task-assignees
        - task.volunteers.each_with_index do |volunteer, i|
          - if i < 5
            = render partial: 'user/user_icon', locals: { user: volunteer, link: true }
          - elsif i == 5
            .more= '...'
      .task-badge.task-badge--users
        i
        = "#{task.volunteers.count}/#{task.volunteer_count_required}"

      .task-badge.task-badge--comments
        i
        = task.comments.count

app/views/circle/tasks/completed.slim
h2= t('.header')

= render partial: 'list', locals: { circle: current_circle, working_group: nil, tasks: @tasks}

app/views/circle/tasks/edit.html.slim
- content_for :header_middle do
  = link_to_back

h2 = t('helpers.header.edit', name: current_task.name)
= render 'form', locals: {delete: true}

app/views/circle/tasks/edit.slim
- content_for :header_middle do
  = link_to_back

h2 = t('helpers.header.edit', name: current_task.name)
= render 'form', locals: {delete: true}

app/views/circle/tasks/my.slim
h2= t('.header')

= render partial: 'list', locals: { circle: current_circle, working_group: nil, tasks: @tasks.open, title: t('.volunteer-header')}

= render partial: 'list', locals: { circle: current_circle, working_group: nil, tasks: @tasks.open_org, title: t('.organizer-header')}

app/views/circle/tasks/new.html.slim
- content_for :header_middle do
  = link_to_back

main.form
  section
    h2 = t('helpers.header.add', name: Task.model_name.human)

    == render 'form', locals: {delete: false}

app/views/circle/tasks/new.slim
- content_for :header_middle do
  = link_to_back

main.form
  section
    h2 = t('helpers.header.add', name: Task.model_name.human)

    == render 'form', locals: {delete: false}

app/views/circle/tasks/open.slim
h2= t('.header')

= render partial: 'list', locals: { circle: current_circle, working_group: nil, tasks: @tasks}

app/views/circle/tasks/show.slim
/ FIXME stop using current_task in this template, call all methods on the presenter.
- task_presenter = ::TaskPresenter.new(current_task)
- content_for :header_middle do
  = link_to_back

.task
  main
    = render 'circle/taskables/taskable_header', taskable: task_presenter

    .item-details-table
      .row.due-date
        .icon
        .title = Task.human_attribute_name(:due_date)
        .details = task_presenter.formatted_date

      .row.duration
        .icon
        .title = Task.human_attribute_name(:duration)
        .details = task_presenter.duration_text

      -if current_task.primary_location.present?
        .row.location
          .icon
          .title = Location.model_name.human
          .details = current_task.primary_location.address

      - current_task.extra_locations.each do |loc|
        v.location
          .icon
          .title = Location.model_name.human
          .details = loc.address

      - if current_task.project.present?
        .row.project
          .icon
          .title = Project.model_name.human
          .details = link_to_project(current_task.project)

      .row.organizer
        .icon
        .title = t('.organized-by', name: "")
        .details
          == cell(:user_icon, current_task.organizer, circle: current_task.circle, link: true)
          = link_to_user(current_task.organizer)
          | &nbsp;
          span.nowrap
            = t('.in_working_group')
            = link_to_working_group(current_task.working_group)

    .task-comments data-url="#{circle_task_comments_path(current_circle, current_task)}"
      = render partial: 'circle/comments/comments', locals: { item: current_task, circle: current_circle, max_display: 5 }

  aside
    .actions
      - if can? :manage, current_task
        = render partial: 'edit_actions', locals: { circle: current_circle, item: current_task }
        
    .users-box
      == cell 'tasks/sourcing_widget', current_task, current_user: current_user