config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_USERNAME'])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_PASSWORD']))
  end unless Rails.env.development?
  mount Sidekiq::Web, at: "/sidekiq"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :circles do
    scope module: 'circle' do
      resource :admin do
        get :roles, :working_groups, :invite, :sponsors, :notifications
        post :activate_member
      end

      resources :members do
        put :activate, :block, :unblock, on: :member
        resources :comments, only: [:create, :index, :destroy, :update]
      end

      resources :roles, :organizers

      resources :supplies do
        put :complete, :volunteer, :decline, :reopen
        resources :comments, only: [:create, :index, :destroy, :update]

        post :invite
      end

      resources :working_groups do
        get :edit_members,    path: '/edit/members'
        get :edit_organizers, path: '/edit/organizers'
        get :edit_projects, path: '/edit/projects'
        patch :add_user
        delete :remove_user

        patch :join, :leave, :activate, :disable

        resources :tasks, only: [:new]
        resources :supplies, only: [:new]
        resources :projects, only: [:new]
      end

      resources :taskables do
        collection do
          get :volunteer
          get :organizer
        end
      end


      resources :tasks do
        collection do
          get :my
          get :open
          get :completed
        end
        resources :comments, only: [:create, :destroy, :update, :index]

        # FIXME task roles need a controller of their own!
        put   :volunteer, :assign_volunteer, :unassign_volunteer, :decline, :complete, :reopen, :clone
        patch :volunteer, :assign_volunteer, :unassign_volunteer, :decline, :complete, :reopen, :clone

        post :invite
      end

      resources :projects do
        post :invite
        put :complete, :reopen
        resources :comments, only: [:create, :destroy, :update, :index]
        resources :tasks, only: [:new]
        resources :supplies, only: [:new]
        resources :files, only: [:create, :destroy, :show]
        resources :files, path: '/files/:uploadable', only: [:new]
        resources :documents, only: :index
      end
      resources :files, only: [:create, :edit, :destroy]
      resources :files, path: '/files/:uploadable', only: [:new]

      resources :documents, only: :index
    end

    resources :files, only: [:show, :update]

  end

  get '/styles', to: 'styleguide#show'

  namespace :user do
    resources :identities
  end

  namespace :api do
    resources :circles, only: [:index]
  end

  get "/register",  to: "user/identities#new", :as => "register"
  post "/register", to: "user/identities#create"

  get  "/join/:circle_id", to: 'circle/invite_flow#join',  as: 'join_circle'
  post "/join/:circle_id", to: 'circle/invite_flow#submit'

  get "/token/:token_code", to: "tokens#handle_token", as: "handle_token"

  scope module: "user" do
    # FIXME none of the resource actions may be needed anymore.
    resources :accounts do
      get :change_password, :switch_circle
      patch :update_password
    end
  end

  scope module: "public" do
    get  "/reset_password", to: 'reset_password_flow#reset_password', as: 'public_reset_password'
    post "/reset_password", to: 'reset_password_flow#submit'
    get "/reset_password/confirmation", to: 'reset_password_flow#confirmation', as: 'public_reset_password_confirmation'
  end

  namespace :public do
    resources :circles, only: [:index, :new, :create] do
      post :join, on: :collection
      get "membership_inactive/:status", action: :membership_inactive, as: :inactive_circle_membership
    end
  end

  get  "/login",  to: "sessions#new",     as: "login"
  post "/login",  to: "sessions#create"
  get  "/logout", to: "sessions#destroy", as: "logout"

  root to: "sessions#new"
  ActiveAdmin.routes(self)
end

app/controllers/api/circles_controller.rb
class Api::CirclesController < ApplicationController
  layout false
  skip_authorization_check

  def index
    @center = params[:location].present? ? Location.location_from(params[:location]) : current_user.location
    locations = Location.near(@center).to_a
    @circles = Circle.joins(:address).where(addresses: { location_id: locations.uniq } )
  end
end

app/controllers/circle/admins_controller.rb
class Circle::AdminsController < ApplicationController
  include HasCircle
  before_action :ensure_logged_in

  before_action do
    authorize! :manage, current_circle
  end

  def show
    @form = Circle::Update.new(user: current_user, circle: current_circle)
  end

  def roles
  end

  def working_groups
  end

  def invite
  end

  def notifications
    @form = Circle::Update.new(user: current_user, circle: current_circle)
  end

  def sponsors
  end

  helper_method def tab_class key
    (action_name == key) ? "#{key} selected" : key
  end
end

app/controllers/circle/comments_controller.rb
class Circle::CommentsController < ApplicationController
  layout "internal"
  before_action :ensure_logged_in
  before_action :set_comment, :only => [:destroy, :update]

  include HasCircle

  def index
    authorize! :read, current_item
    if can? :create, Comment, current_item, current_circle
      @form = Comment::Create.new(commenter: current_user, item: current_item, comment: Comment.new)
    end
    render layout: false
  end

  def create
    authorize! :create, Comment, current_item, current_circle

    @comment = Comment.new
    @form = Comment::Create.new(params[:comment], commenter: current_user, item: current_item, comment: @comment)

    outcome = @form.submit

    if outcome.success?
      redirect_to circle_commentable_path(current_circle, current_item),
      notice: t('flash.created', name: Comment.model_name.human)
    else
      redirect_to circle_commentable_path(current_circle, current_item),
      alert: t('flash.failed.create', name: Comment.model_name.human)
    end
  end

  def update
    authorize! :update, Comment, current_item, current_circle

    @form = Comment::Update.new(params[:comment], commenter: current_user, item: current_item, comment: @comment)

    outcome = @form.submit

    respond_to do |format|
      if outcome.success?
        format.html { redirect_to circle_commentable_path(current_circle, current_item) }
        format.json { head :no_content }
      else
        format.html { redirect_to circle_commentable_path(current_circle, current_item) }
        format.json { render json: outcome.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :update, Comment, current_item, current_circle

    @comment.destroy

    redirect_to circle_commentable_path(current_circle, current_item),
                notice: t('flash.destroy', name: Comment.model_name.human)
  end

  helper_method def current_item
    @item ||= if params[:supply_id].present?
                Supply.find(params[:supply_id])
              elsif params[:member_id].present?
                User.find(params[:member_id])
              elsif params[:project_id].present?
                Project.find(params[:project_id])
              else
                Task.find(params[:task_id])
              end
  end

  helper_method def page
    @page ||= OpenStruct.new.tap do |page|
    end
  end

  private

    def set_comment
      @comment = current_item.comments.find(params[:id])
    end

    def circle_commentable_path(circle, item)
      if item.is_a? Supply
        circle_supply_path(circle, item)
      elsif item.is_a? User
        circle_member_path(circle, item)
      elsif item.is_a? Project
        circle_project_path(circle, item)
      else
        circle_task_path(circle, item)
      end
    end
end

app/controllers/circle/documents_controller.rb
class Circle::DocumentsController < ApplicationController

  skip_authorization_check # TODO: REMOVE

  include HasCircle

  before_action :ensure_logged_in
  before_action :set_back_path, only: [:index]

  def index
    authorize! :read, current_circle

    @circle_files = current_circle.files.select{ |f| can?(:read, f) }
    @circle_links = [] # current_circle.links.select{ |f| can?(:read, f) }

    @working_group_files = FileUpload.where(uploadable: current_circle.working_groups).select { |f| can?(:read, f) }
    @working_group_links = [] # links.select{ |f| can?(:read, f) }

    @project_files = FileUpload.where(uploadable: current_circle.projects).select { |f| can?(:read, f) }
    @project_links = [] # current_circle.links.select{ |f| can?(:read, f) }
  end
end

app/controllers/circle/files_controller.rb
class Circle::FilesController < ApplicationController
  include HasCircle

  before_action :ensure_logged_in, except: :show
  skip_before_action EnsureActiveUser, only: :show

  skip_authorization_check

  def show
    file = FileUpload.find(params[:id])
    authorize! :read, file

    if stale? file
      expires_in(1.hour, public: false)
      filename = file.name + file.file_extension
      disposition = params.has_key?(:download) ? 'attachment' : 'inline'
      send_data file.read, disposition: disposition, filename: filename, type: file.file_content_type
    end

  rescue => e
    Rails.logger.warning "#{e.message}: user: #{current_user.id} file: #{params[:id]}"
    render nothing: true, status: :not_found
  end

  def new
    @form = FileUpload::CreateForm.new(uploadable_gid: params[:uploadable], redirect_path: URI(request.referer || '').path)
    authorize! :manage, @form.uploadable
  end

  def create
    @form = FileUpload::CreateForm.new(params[:file_upload], uploader: current_user)
    authorize! :manage, @form.uploadable
    outcome = @form.submit
    if outcome.success?
      redirect_to @form.redirect_path, notice: t('flash.file_uploads.created')

    else
      errors.add outcome.errors
      render :new
    end
  end

  def edit
    file = FileUpload.find(params[:id])
    authorize! :manage, file
    @form = FileUpload::UpdateForm.new(file_upload: file, redirect_path: URI(request.referer || '').path)
  end

  def update
    file = FileUpload.find(params[:id])
    authorize! :manage, file
    @form = FileUpload::UpdateForm.new(params[:file_upload], file_upload: file)
    outcome = @form.submit
    if outcome.success?
      redirect_to @form.redirect_path, notice: t('flash.file_uploads.updated')

    else
      errors.add outcome.errors
      render :edit
    end
  end

  def destroy
    FileUpload::Destroy.run!( user: current_user, file: FileUpload.find(params[:id]) )
    redirect_to :back
  end
end

app/controllers/circle/invite_flow_controller.rb
class Circle::InviteFlowController < ApplicationController
  skip_authorization_check
  layout 'public'

  def join
    form
  end

  def submit
    outcome = if current_user.present?
      Circle::Join.run(user: current_user, circle_id: circle.id)
    else
      form.submit
    end

    if outcome.success?
      login(outcome.result) unless current_user
      redirect_to circle_path(circle)

    else
      errors.add outcome.errors
      render :join
    end
  end

  helper_method def form
    @form ||= User::Create.new(params[:user] || {}, circle: circle)
  end

  helper_method def circle
    @circle ||= Circle.find_by(id: params[:circle_id])
  end
  alias_method :current_circle, :circle

  before_action do
    @skip_registration_links = true
    redirect_to root_url unless circle.present?
  end
end

app/controllers/circle/members_controller.rb
#
# a "Member" is a user in a circle. Technically this is implemented
# with roles; a user is member in a circle if (s)he has a circle_role.
#
class Circle::MembersController < ApplicationController

  before_action :ensure_logged_in
  before_action :set_back_path, only: :index

  include HasCircle

  def index
    authorize! :read, current_circle
    @members    = active_users.select { |member| can?(:read, member, current_circle) }
    @organizers = organizers.select { |member| can?(:read, member, current_circle) }
    @totals     = { members: active_users.count, organizers: organizers.count }
    respond_to do |format|
      format.html
      format.csv { send_data(generate_csv(@members)) }
      format.pdf do
        render  pdf: "#{current_circle.name}_" + t("pdf.list") + "_" + Date.today.to_formatted_s(:number),
                template: 'circle/members/pdf.slim',
                layout: 'pdf.slim',
                locals: { members: @members },
                orientation: 'Landscape'
      end
    end
  end

  def show
    authorize! :read, current_member, current_circle
    if can? :create, Comment.new, current_member, current_circle
      @form = Comment::Create.new(commenter: current_user, item: current_member, comment: Comment.new)
    end
  end

  def edit
    authorize! :edit, current_member, current_circle
    @form = User::Update.new(user: current_member, current_circle: current_circle)
  end

  def update
    authorize! :edit, current_member, current_circle
    @form = User::Update.new(params[:user], user: current_member, current_circle: current_circle)
    outcome = @form.submit
    errors.add outcome.errors
    if outcome.success?
      flash[:notice] = t("flash.user.account.saved")
      redirect_to circle_member_url(current_circle, current_member)
    else
      flash[:error] = t("flash.user.account.save-failed")
      render :edit
    end
  end

  def activate
    authorize! :activate_member, current_circle
    outcome = Circle::Member::Activate.run(params.merge(admin: current_user))
    if request.xhr?
      head (outcome ? :ok : :unprocessable_entity)
    else
      redirect_to circle_member_path(current_circle, current_member)
    end
  end


  def block
    authorize! :block, current_member, current_circle
    Circle::Member::Block.run(params.merge(admin: current_user))
    redirect_to circle_member_path(current_circle, current_member)
  end


  def unblock
    authorize! :unblock, current_member, current_circle
    Circle::Member::Unblock.run(params.merge(admin: current_user))
    redirect_to circle_member_path(current_circle, current_member)
  end


  helper_method def current_member
    @current_member ||= current_circle.users.find(params[:id])
  end

  private

  def active_users
    @_active_users ||= current_circle.users.active
      .includes(:identity, :working_groups, :circle_roles)
      .order('last_name asc')
  end

  def generate_csv(members)
    template = "circle/members/index.csv.slim"
    content = render_to_string(template, layout: false, locals: { members: members })
  end

  def organizers
    @_organizers ||= begin
      circle_organizers = User.
          select('users.id, count(*) as role_count').
          joins(:circle_roles).
          where(circle_roles: { role_type: Circle::Role::ORGANIZER_TYPE_IDS, circle: current_circle }).
          group('users.id')

      working_group_organizers = User.
          select('users.id, count(*) as role_count').
          joins(:working_group_roles).
          where(working_group_roles: { role_type: WorkingGroup::Role::ORGANIZER_TYPE_IDS, working_group_id: current_circle.working_groups }).
          group('users.id')

      counts = (circle_organizers + working_group_organizers).each_with_object(Hash.new) do |user, obj|
        obj[user.id] ||= 0
        obj[user.id] += user.role_count
      end

      all_organizers = User.where(id: counts.keys).includes(:identity, :working_groups, :circle_roles)

      all_organizers.sort_by { |u| -counts[u.id] }
    end
  end

end

app/controllers/circle/organizers_controller.rb
class Circle::OrganizersController < ApplicationController

  skip_authorization_check # TODO: REMOVE

  include HasCircle

  before_action :ensure_logged_in
  before_action :set_back_path, only: [:index]

  def index
    circle_organizers = User.
      select('users.id, count(*) as role_count').
      joins(:circle_roles).
      where(circle_roles: { role_type: Circle::Role::ORGANIZER_TYPE_IDS, circle: current_circle }).
      group('users.id')

    working_group_organizers = User.
      select('users.id, count(*) as role_count').
      joins(:working_group_roles).
      where(working_group_roles: { role_type: WorkingGroup::Role::ORGANIZER_TYPE_IDS, working_group_id: current_circle.working_groups }).
      group('users.id')

    counts = (circle_organizers + working_group_organizers).each_with_object(Hash.new) do |user, obj|
      obj[user.id] ||= 0
      obj[user.id] += user.role_count
    end

    all_organizers = User.where(id: counts.keys).includes(:identity, :working_groups, :circle_roles)

    @members = all_organizers.sort_by{|u| -counts[u.id] }
  end
end

app/helpers/circle/members_helper.rb
module Circle::MembersHelper
  def circle_admins_with_links
  end
end

app/views/circle/admins/_inactive_members_list.slim
table.default-table.member-list
  tr
    th
    th.name = User.human_attribute_name("name")
    th = User.human_attribute_name("location.address")
    th = User.human_attribute_name("phone")
    th = User.human_attribute_name("email")
    th = User.human_attribute_name("active_since")
    th

  - users.each do |user|
    tr
      td
        == cell(:user_icon, user, circle: current_circle, link: true)

      td.name
        = link_to user.name, circle_member_path(current_circle, user)

      td = user.address.full_address

      td
        - if user.mobile_phone != nil
          div= "M: #{user.mobile_phone}"
        - if user.home_phone != nil
          div= "H: #{user.home_phone}"

      td
        a href="mailto:#{user.identity.email}"
        = user.identity.email

      td= l(user.circle_roles.find_by(circle: current_circle).updated_at.to_date, format: :default)

      td
        = button_to t('.activate'), activate_circle_member_path(current_circle, user), remote: true, method: :put, class: 'activate_pending_user'

app/views/circle/admins/_nav.slim
.tab-nav.tab-nav-no-js

  a class=tab_class('show') href=circle_admin_path(current_circle)
    = t('.basic-settings')
  a class=tab_class('roles') href=roles_circle_admin_path(current_circle)
    = t('.roles')
  a class=tab_class('working_groups') href=working_groups_circle_admin_path(current_circle)
    = t('.working-groups')
  a class=tab_class('invite') href=invite_circle_admin_path(current_circle)
    - if pending_admin_actions?
      i.before-icon class="fa fa-circle"
    = t('.invite-volunteers')
  - if current_circle.sponsorships.current.present?
    a class=tab_class('sponsors') href=sponsors_circle_admin_path(current_circle)
      = Sponsor.model_name.human.pluralize.capitalize
  a class=tab_class('notifications') href=notifications_circle_admin_path(current_circle)
    = t('.notifications')

app/views/circle/admins/invite.slim
= render partial: 'nav'

section.circle-admin

  h2 = t('.invite_headline')

  p = t('.invite_members_explaination')

  .invite-link.copy-box
    input id="invite-url" type="copy" readonly="" value=join_circle_url(current_circle)
    button type="submit" data-clipboard-target="input#invite-url"

section.circle-admin

  h2 = t('.blocked_members_headline')

  - if current_circle.users.blocked.empty?
    p = t('.no_blocked_members_message')
  - else
    p = t('.blocked_members_explanation')
    - users = current_circle.users.blocked.order('created_at DESC')
    = render partial: 'inactive_members_list', locals: { users: users }

- if current_circle.must_activate_users
  section.circle-admin

    h2 = t('.pending_members_headline')

    - if current_circle.users.pending.empty?
      p = t('.no_pending_members_message')
    - else
      p = t('.pending_members_explanation')
      - users = current_circle.users.pending.order('created_at DESC')
      = render partial: 'inactive_members_list', locals: { users: users }

app/views/circle/admins/notifications.slim
= render partial: 'nav'

section.circle-admin

  h2 = t('.headline')

  = form_for @form, url: circle_path(current_circle) do |f|
    - if errors.present?
      .form-introduction.error
        p= t('error_correction')

    table.default-table
      tbody
        tr
          td = f.check_box :notify_on_task_change
          td = f.label :notify_on_task_change
        tr
          td = f.check_box :notify_on_task_comment
          td = f.label :notify_on_task_comment


    .actions.submit-row
      = f.submit

app/views/circle/admins/roles.slim
= render partial: 'nav'

section.circle-admin
  = form_tag circle_roles_path(current_circle), method: 'POST' do
    table.default-table
      thead
        tr
          th= User.human_attribute_name("role")
          th= User.model_name.human
          th= User.human_attribute_name("role.status")
          th= User.human_attribute_name("role.actions")
      tbody
        - current_circle.roles.leadership.order('role_type ASC, name ASC').each do |role|
          tr
            td = role.name
            td = link_to_user(role.user)
            td = Circle::Role.human_enum_name(:status, role.status)
            td.actions
              - if can? :delete, role
                = link_to '', circle_role_path(current_circle, role), class: 'delete', method: 'delete', data: { confirm: t('.confirm_delete_circle') }

      tfoot
        - if can? :manage, current_circle
          tr#add-role.action-row
            td colspan="3"
              a href="#" = t('.promote_user')
          tr#add-role-fields.hidden
            td
              = select_tag "circle_role[role_type]", options_for_select(Circle::Role.leadership_role_types_with_names)
              = text_field_tag "circle_role[name]", nil, class: 'hidden'
            td= select_tag "circle_role[user_id]", options_from_collection_for_select(current_circle.volunteers.active, :id, :name)
            td= submit_tag t('.save')

app/views/circle/admins/show.slim
= render partial: 'circle/admins/nav'

section.circle-admin
  = render partial: 'circles/form', locals: { form: @form, url: circle_path(current_circle) }

app/views/circle/admins/sponsors.slim
= render partial: 'nav'

section.circle-admin
  table.default-table
    tr
      th= Sponsor.model_name.human
      th= Sponsorship.human_attribute_name(:starts_on)
      th= Sponsorship.human_attribute_name(:ends_on)

    - current_circle.sponsorships.current.order(ends_on: :asc).each do |sponsorship|
      tr
        td = sponsorship.sponsor.name
        td = l(sponsorship.starts_on)
        td = l(sponsorship.ends_on)

app/views/circle/admins/working_groups.slim
= render partial: 'nav'

section.circle-admin

  == cell('working_groups/table', current_circle, working_groups: current_circle.working_groups.active.asc_order, status: :active)

section.circle-admin
  
  == cell('working_groups/table', current_circle, working_groups: current_circle.working_groups.disabled.asc_order, status: :deactivated)